feat(schema): create schemas or models of dropouts
Laboratoria/models pull request #73
Opened 2020-10-19 13:56 UTC by betsyvies

Well, create schemas and unit test for dropouts.

2020-10-19 14:16 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +  }, { collection: 'dropouts' });
```suggestion
  }, { collection: 'dropouts', timestamps: true  });
```
ref: https://mongoosejs.com/docs/guide.html#timestamps, why? it could be too useful to know when a dropout was created and updated, in case we update the dropout to correct some fields

2020-10-19 14:21 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +    codeStudent: {
```suggestion
    studentCode: {
```

2020-10-19 14:24 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +module.exports = (conn) => {
I think we can add comments so that we can know what each field is for. Let's add just for fields that are unclear like `when`, `studentCode`, `stage`, `sad`, `type`, `observations`. Examples would be helpful

2020-10-19 14:26 UTC, raulingg requested changes
I left some comments. TAL when you get a chance. Feel free to ask if you are in doubt about a comment.

2020-10-20 19:09 UTC, raulingg commented on src/__tests__/Dropout.spec.js
> +  it('should fail when user not ObjecId', () => {
```suggestion
  it('should fail validation when user is not an ObjectId', () => {
```

2020-10-20 19:13 UTC, raulingg commented on src/__tests__/Dropout.spec.js
> +      });
We should test if the dropout is created in the database, but instead we are expecting an error.

2020-10-20 19:13 UTC, raulingg commented on src/__tests__/Dropout.spec.js
> +  it('should successful when user does exist', async () => {
```suggestion
  it('should create a new dropout', async () => {
```

2020-10-20 19:15 UTC, raulingg commented on src/__tests__/Dropout.spec.js
> +  it('should fail validation when missing fields are provided', () => {
```suggestion
  it('should fail validation when fields are missing', () => {
```

2020-10-20 19:24 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +    // It means how she leave the program, Leave the program voluntarily
```suggestion
    // The way a student leaves the bootcamp, for example
    // invitedToLeave, she is invited to leave literally
    // dropout, she leaves voluntarily 
```

2020-10-20 19:26 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +    // It means to the date of the dropout
```suggestion
    //  date when the student leaves the bootcamp
```

2020-10-20 19:28 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +    // It refers to the student code, for example: LIM022222
I think it's not enough. I'm still questions about the procedence, creation, when

Let's gather more information about `studentCode` field talking further with Diego or Rocio.

2020-10-20 19:31 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +    // It refers to the stage in which she leave the program, for example: 1st day
```suggestion
    // the stage in which a student leaves the bootcamp, for example: "1st day", "proyect 1" 
```

2020-10-20 19:34 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +    // It means to how the BC team see her
```suggestion
    // The bootcamp team's observations about the student
```

2020-10-20 19:36 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +    // It means if the BC team is sad, because she is leaving
```suggestion
    // is the bootcamp team sad because of the droput? true or false
```

2020-10-20 19:37 UTC, raulingg commented on src/schemas/DropoutSchema.js
> +    // It refers to other reason, for example: coronavirus
```suggestion
    // additonal reasons for the dropout, for example: coronavirus
```

2020-10-20 19:39 UTC, raulingg requested changes
@betsyvies good job. 

I left commets to enhance wording.

2020-10-20 20:48 UTC, betsyvies commented on src/__tests__/Dropout.spec.js
> +  it('should fail validation when missing fields are provided', () => {
It's true! So, I delete this test

2020-10-21 15:29 UTC, raulingg approved these changes
LGTM :+1

2020-10-21 15:37 UTC, merged